/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.clientes;

import controller.passageiroDao;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Passageiro;
import view.adm.formGerenciar;

/**
 *
 * @author italo.bcsilva
 */
public class formLogin extends javax.swing.JFrame {

    /**
     * Creates new form formLogin
     */
    public formLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        txtLogin = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jScrollBar1.setRequestFocusEnabled(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(142, 157, 204));
        setMinimumSize(new java.awt.Dimension(977, 506));
        setSize(new java.awt.Dimension(977, 506));
        getContentPane().setLayout(null);

        txtLogin.setName("txtLogin"); // NOI18N
        txtLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLoginMouseClicked(evt);
            }
        });
        getContentPane().add(txtLogin);
        txtLogin.setBounds(310, 190, 295, 37);
        getContentPane().add(filler1);
        filler1.setBounds(982, 423, 0, 0);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGIN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 90, 90, 50);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EMAIL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 160, 105, 43);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SENHA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 250, 105, 43);

        btnEntrar.setBackground(new java.awt.Color(142, 157, 204));
        btnEntrar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.setName("btnEntrar"); // NOI18N
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(390, 350, 170, 40);

        txtSenha.setName("txtSenha"); // NOI18N
        txtSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(310, 280, 295, 37);

        jLabel3.setBackground(new java.awt.Color(125, 132, 178));
        jLabel3.setForeground(new java.awt.Color(125, 132, 178));
        jLabel3.setText("LOGIN");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 80, 350, 340);

        btnCadastro.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Criar conta");
        btnCadastro.setName("btnCadastro"); // NOI18N
        btnCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastroMouseClicked(evt);
            }
        });
        getContentPane().add(btnCadastro);
        btnCadastro.setBounds(530, 400, 120, 60);

        jLabel8.setText("jLabel7");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 340, 50, 50);

        jLabel9.setText("jLabel7");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 340, 50, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginMouseClicked

    private void txtSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenhaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaMouseClicked

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // TODO add your handling code here:
        String login = this.txtLogin.getText();
        String senha = this.txtSenha.getText();
        passageiroDao p = new passageiroDao();
        formGerenciar gerenciar = new formGerenciar();
        Passageiro obj = new Passageiro();
        
        if(login.equals("admin") && senha.equals("1234")){
            gerenciar.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(false);
        gerenciar.setVisible(true);    
        }
        
        else {
            try{
                ResultSet resul = p.validarLogin(login, senha);
                if(resul.next())
                {
                    JOptionPane.showMessageDialog(null, "Login realizado - seja bem-vindo " +login + " compre sua passagem e viaje com segurança", "Foi", JOptionPane.WARNING_MESSAGE);
                    this.setVisible(false);
                    formConsultaPassagem pass = new formConsultaPassagem();
                    pass.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null, "Usuário ou senha invalidos, verifique ou faça o cadastro", "Foi", JOptionPane.WARNING_MESSAGE);

                }
            }catch(SQLException err) {
                JOptionPane.showMessageDialog(null, "Erro ao Buscar usuário!" + err.getMessage());
                JOptionPane.showMessageDialog(null, "Login ou Senha Inválidos", "Erro de operação", JOptionPane.WARNING_MESSAGE);

                return; 
            }
        }
        //else {
            //JOptionPane.showMessageDialog(null, "Usuário não cadastrado, faça seu cadastro e não perca mais tempo!");
        //}



    }//GEN-LAST:event_btnEntrarMouseClicked

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseClicked
        // TODO add your handling code here:
        formCadPassageiro cadastro = new formCadPassageiro();
        cadastro.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(false);
        cadastro.setVisible(true);
    }//GEN-LAST:event_btnCadastroMouseClicked

    /**
     * 
     * 
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                formLogin tela = new formLogin();
                tela.setExtendedState(JFrame.MAXIMIZED_BOTH);
                tela.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCadastro;
    private javax.swing.JButton btnEntrar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
