/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.clientes;

import controller.passageiroDao;
import javax.swing.table.DefaultTableModel;
import model.Passageiro;
import controller.conectarDao;


/**
 *
 * @author thiag
 */
public class formCadastroPassageiro extends javax.swing.JFrame {

    /**
     * Creates new form formCadas
     */
    public formCadastroPassageiro() {
        initComponents();
        passageiroDao u = new passageiroDao();
        u.criarBanco();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        textTelefone = new javax.swing.JTextField();
        textSenha = new javax.swing.JTextField();
        textCPF = new javax.swing.JTextField();
        textIdade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCadastra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Criar Conta");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 30, 140, 20);

        textEmail.setName("txtEmail"); // NOI18N
        getContentPane().add(textEmail);
        textEmail.setBounds(30, 80, 410, 30);
        getContentPane().add(textNome);
        textNome.setBounds(30, 140, 410, 30);

        textTelefone.setName("txtFone"); // NOI18N
        getContentPane().add(textTelefone);
        textTelefone.setBounds(30, 200, 160, 30);

        textSenha.setName("txtSenha"); // NOI18N
        getContentPane().add(textSenha);
        textSenha.setBounds(30, 260, 160, 30);

        textCPF.setName("txtCpf"); // NOI18N
        getContentPane().add(textCPF);
        textCPF.setBounds(230, 260, 200, 30);

        textIdade.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        textIdade.setForeground(new java.awt.Color(204, 204, 204));
        textIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(textIdade);
        textIdade.setBounds(230, 200, 99, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senha");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 240, 100, 19);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 60, 19);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 120, 60, 19);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Idade");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 180, 100, 19);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CPF");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 240, 100, 19);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefone");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 180, 100, 19);

        btnCadastra.setBackground(new java.awt.Color(51, 51, 51));
        btnCadastra.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnCadastra.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastra.setText("Cadastar");
        btnCadastra.setName("btnCadastra"); // NOI18N
        btnCadastra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastraMouseClicked(evt);
            }
        });
        btnCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastra);
        btnCadastra.setBounds(30, 310, 140, 33);

        jLabel3.setBackground(new java.awt.Color(125, 132, 178));
        jLabel3.setForeground(new java.awt.Color(125, 132, 178));
        jLabel3.setText("fundo");
        jLabel3.setMaximumSize(new java.awt.Dimension(1200, 580));
        jLabel3.setMinimumSize(new java.awt.Dimension(1200, 580));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(1200, 580));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1200, 580, 1200, 580);

        jPanel2.setBackground(new java.awt.Color(125, 132, 178));
        jPanel2.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 830, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastraMouseClicked
        // TODO add your handling code here:
       passageiroDao u = new passageiroDao();
       Passageiro passageiro = new Passageiro();
       
       String cpf = textCPF.getText();
       String nome = textNome.getText();
       String telefone = textTelefone.getText();
       String email = textEmail.getText();
       String senha = textSenha.getText();
       int idade = Integer.parseInt(textIdade.getText());
       
       passageiro.setCpf(cpf);
       passageiro.setEmail(email);
       passageiro.setNome(nome);
       passageiro.setIdade(idade);
       passageiro.setTelefone(telefone);
       passageiro.setSenha(senha);
       
       u.Incluir(passageiro);
    }//GEN-LAST:event_btnCadastraMouseClicked

    private void textIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdadeActionPerformed

    private void btnCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCadastroPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCadastroPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCadastroPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCadastroPassageiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCadastroPassageiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textCPF;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textIdade;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textSenha;
    private javax.swing.JTextField textTelefone;
    // End of variables declaration//GEN-END:variables
}
