/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author alesandro.rsjunior
 */
public class formGerenciar extends  javax.swing.JFrame {

    /**
     * Creates new form TelaDeADM
     */
    public formGerenciar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnMotorista = new javax.swing.JButton();
        btnGrcRotas = new javax.swing.JButton();
        btnPassagem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(125, 132, 178));

        btnUsuario.setBackground(new java.awt.Color(142, 157, 204));
        btnUsuario.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setText("Gerenciar usuários");
        btnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseClicked(evt);
            }
        });

        btnMotorista.setBackground(new java.awt.Color(142, 157, 204));
        btnMotorista.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnMotorista.setForeground(new java.awt.Color(255, 255, 255));
        btnMotorista.setText("Gerenciar morotistas");
        btnMotorista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMotoristaMouseClicked(evt);
            }
        });

        btnGrcRotas.setBackground(new java.awt.Color(142, 157, 204));
        btnGrcRotas.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnGrcRotas.setForeground(new java.awt.Color(255, 255, 255));
        btnGrcRotas.setText("Gerenciar rotas");
        btnGrcRotas.setName(""); // NOI18N
        btnGrcRotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGrcRotasMouseClicked(evt);
            }
        });
        btnGrcRotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrcRotasActionPerformed(evt);
            }
        });

        btnPassagem.setBackground(new java.awt.Color(142, 157, 204));
        btnPassagem.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnPassagem.setForeground(new java.awt.Color(255, 255, 255));
        btnPassagem.setText("Gerenciar passagem");
        btnPassagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPassagemMouseClicked(evt);
            }
        });
        btnPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPassagemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Deslogar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGrcRotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPassagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnMotorista)
                .addGap(18, 18, 18)
                .addComponent(btnGrcRotas)
                .addGap(18, 18, 18)
                .addComponent(btnPassagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPassagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPassagemActionPerformed

    private void btnGrcRotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrcRotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrcRotasActionPerformed

    private void btnGrcRotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrcRotasMouseClicked
        formCadastroRotas rot = new formCadastroRotas();
        
        this.setVisible(false);
        rot.setVisible(true);
    }//GEN-LAST:event_btnGrcRotasMouseClicked

    private void btnMotoristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMotoristaMouseClicked
        // TODO add your handling code here:
        formConsultaMotorista mot = new formConsultaMotorista();
        
        this.setVisible(false);
        mot.setVisible(true);
    }//GEN-LAST:event_btnMotoristaMouseClicked

    private void btnUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseClicked
        // TODO add your handling code here:
        formConsultaDeUSU usu = new formConsultaDeUSU();
        
        this.setVisible(false);
        usu.setVisible(true);
    }//GEN-LAST:event_btnUsuarioMouseClicked

    private void btnPassagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPassagemMouseClicked
        // TODO add your handling code here:
        formConsultaPassagem pass = new formConsultaPassagem();
        
        this.setVisible(false);
        pass.setVisible(true);
    }//GEN-LAST:event_btnPassagemMouseClicked

        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formConsultaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formConsultaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formConsultaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formConsultaMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formGerenciar().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrcRotas;
    private javax.swing.JButton btnMotorista;
    private javax.swing.JButton btnPassagem;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}



