/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.adm;

import controller.passageiroDao;
import controller.conectarDao;
import javax.swing.table.DefaultTableModel;
import model.Passageiro;

/**
 *
 * @author thiag
 */
public class formCadastroAdm extends javax.swing.JFrame {

    /**
     * Creates new form formCadas
     */
    public formCadastroAdm() {
        initComponents();
        passageiroDao p = new passageiroDao();
        p.criarBanco();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        ds_email = new javax.swing.JTextField();
        ds_nome = new javax.swing.JTextField();
        ds_telefone = new javax.swing.JTextField();
        ds_senha = new javax.swing.JTextField();
        ds_cpf = new javax.swing.JTextField();
        ds_idade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCadastra = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCadastra1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setBackground(new java.awt.Color(153, 153, 255));
        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cadastrar conta");
        jLabel4.setAutoscrolls(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, -10, 200, 80);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Email", "Telefone", "Data", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(610, 70, 530, 480);

        ds_email.setName("txtEmail"); // NOI18N
        getContentPane().add(ds_email);
        ds_email.setBounds(30, 90, 390, 40);
        getContentPane().add(ds_nome);
        ds_nome.setBounds(30, 180, 390, 40);

        ds_telefone.setName("txtFone"); // NOI18N
        getContentPane().add(ds_telefone);
        ds_telefone.setBounds(30, 270, 270, 40);

        ds_senha.setName("txtSenha"); // NOI18N
        getContentPane().add(ds_senha);
        ds_senha.setBounds(30, 350, 170, 40);

        ds_cpf.setName("txtCpf"); // NOI18N
        getContentPane().add(ds_cpf);
        ds_cpf.setBounds(220, 350, 230, 40);

        ds_idade.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        ds_idade.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(ds_idade);
        ds_idade.setBounds(320, 270, 100, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SENHA ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 320, 100, 26);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMAIL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 60, 26);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOME");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 150, 60, 26);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("idade");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 240, 230, 26);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CPF");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 320, 100, 26);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TELEFONE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 240, 100, 26);

        btnAlterar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setName("btnAlterar"); // NOI18N
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(180, 430, 120, 33);

        btnExcluir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setName("btnExcluir"); // NOI18N
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(1020, 560, 120, 33);

        btnCadastra.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnCadastra.setForeground(new java.awt.Color(51, 51, 51));
        btnCadastra.setText("Cadastrar");
        btnCadastra.setName("btnCadastra"); // NOI18N
        btnCadastra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastraMouseClicked(evt);
            }
        });
        btnCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastra);
        btnCadastra.setBounds(30, 430, 140, 33);

        btnBuscar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setName("btnExcluir"); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(610, 560, 110, 33);

        jLabel3.setBackground(new java.awt.Color(125, 132, 178));
        jLabel3.setForeground(new java.awt.Color(125, 132, 178));
        jLabel3.setText("fundo");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-140, -10, 1420, 698);

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("DD");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 270, 33, 45);

        btnCadastra1.setBackground(new java.awt.Color(51, 51, 51));
        btnCadastra1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btnCadastra1.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastra1.setText("CADASTRAR ");
        btnCadastra1.setName("btnCadastra"); // NOI18N
        btnCadastra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastra1MouseClicked(evt);
            }
        });
        getContentPane().add(btnCadastra1);
        btnCadastra1.setBounds(580, 420, 200, 33);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastraMouseClicked
       passageiroDao u = new passageiroDao();
       Passageiro passageiro = new Passageiro();
       
       String cpf = ds_cpf.getText();
       String nome = ds_nome.getText();
       String telefone = ds_telefone.getText();
       String email = ds_email.getText();
       String senha = ds_senha.getText();
       int idade = Integer.parseInt(ds_idade.getText());
       
       passageiro.setCpf(cpf);
       passageiro.setEmail(email);
       passageiro.setNome(nome);
       passageiro.setIdade(idade);
       passageiro.setTelefone(telefone);
       passageiro.setSenha(senha);
       
       u.cadastrar(passageiro);
    }//GEN-LAST:event_btnCadastraMouseClicked

    private void btnCadastra1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastra1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastra1MouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       passageiroDao u = new passageiroDao();
       Passageiro passageiro = new Passageiro();
       
       String cpf = ds_cpf.getText();
       String nome = ds_nome.getText();
       String telefone = ds_telefone.getText();
       String email = ds_email.getText();
       String senha = ds_senha.getText();
       int idade = Integer.parseInt(ds_idade.getText());
       
       passageiro.setCpf(cpf);
       passageiro.setEmail(email);
       passageiro.setNome(nome);
       passageiro.setIdade(idade);
       passageiro.setTelefone(telefone);
       passageiro.setSenha(senha);
        
        u.Alterar(passageiro);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraActionPerformed
 
    }//GEN-LAST:event_btnCadastraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCadastroAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCadastroAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastra;
    private javax.swing.JButton btnCadastra1;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JTextField ds_cpf;
    private javax.swing.JTextField ds_email;
    private javax.swing.JTextField ds_idade;
    private javax.swing.JTextField ds_nome;
    private javax.swing.JTextField ds_senha;
    private javax.swing.JTextField ds_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
